-- MYSHORT APP - SUPABASE DATABASE SCHEMA
-- Jalankan seluruh file ini di Supabase SQL Editor.
-- File ini sengaja tidak memakai DROP TABLE/DROP POLICY/DROP TRIGGER,
-- sehingga lebih aman untuk project baru dan tidak menghapus data tabel.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  uid text unique not null default ('MS' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,10))),
  username text unique not null,
  full_name text not null default 'Member',
  email text not null,
  phone text,
  referral_code text unique not null,
  referred_by_code text,
  status text not null default 'Aktif',
  level text not null default 'LV 1',
  xp integer not null default 0,
  role text not null default 'member' check (role in ('member','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wallets (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  balance numeric(18,2) not null default 0,
  total_in numeric(18,2) not null default 0,
  total_out numeric(18,2) not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.missions (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  reward numeric(18,2) not null default 0 check (reward >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.user_missions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  mission_id bigint not null references public.missions(id) on delete cascade,
  status text not null default 'completed',
  claimed_reward numeric(18,2) not null default 0,
  completed_at timestamptz,
  unique(user_id, mission_id)
);

create table if not exists public.referrals (
  id bigint generated by default as identity primary key,
  referrer_id uuid not null references public.profiles(id) on delete cascade,
  referred_id uuid not null unique references public.profiles(id) on delete cascade,
  referral_code text not null,
  status text not null default 'registered',
  reward numeric(18,2) not null default 5000,
  created_at timestamptz not null default now()
);

create table if not exists public.bank_accounts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  method text not null,
  account_number text not null,
  account_name text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.withdrawals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  amount numeric(18,2) not null check (amount > 0),
  method text not null,
  account_number text not null,
  account_name text not null,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  admin_note text,
  created_at timestamptz not null default now(),
  processed_at timestamptz
);

create table if not exists public.deposits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  amount numeric(18,2) not null check (amount > 0),
  method text not null default 'DANA',
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  proof_url text,
  admin_note text,
  created_at timestamptz not null default now(),
  processed_at timestamptz
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null,
  amount numeric(18,2) not null,
  reference_id bigint,
  description text,
  created_at timestamptz not null default now()
);

-- Kompatibilitas bila sebagian tabel sudah pernah dibuat.
alter table public.profiles add column if not exists role text not null default 'member';
alter table public.profiles add column if not exists xp integer not null default 0;
alter table public.wallets add column if not exists total_in numeric(18,2) not null default 0;
alter table public.wallets add column if not exists total_out numeric(18,2) not null default 0;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

create or replace function public.generate_referral_code(p_username text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  base text;
  code text;
begin
  base := upper(regexp_replace(coalesce(p_username,'USER'),'[^A-Za-z0-9]','','g'));
  base := left(base,4);
  if length(base) < 3 then base := 'USER'; end if;
  loop
    code := base || floor(random()*900000+100000)::text;
    exit when not exists(select 1 from public.profiles where referral_code=code);
  end loop;
  return code;
end;
$$;

create or replace function public.generate_unique_username(p_username text, p_email text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  base text;
  candidate text;
  i int := 0;
begin
  base := lower(regexp_replace(coalesce(nullif(p_username,''),split_part(coalesce(p_email,'user'),'@',1)),'[^a-zA-Z0-9_]','','g'));
  if base='' then base:='user'; end if;
  candidate:=left(base,25);
  while exists(select 1 from public.profiles where lower(username)=lower(candidate)) loop
    i:=i+1;
    candidate:=left(base,20)||i::text;
  end loop;
  return candidate;
end;
$$;

-- Membuat profile + wallet + bonus referral otomatis ketika akun Auth dibuat.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  ref text;
  referrer uuid;
  new_username text;
  new_code text;
  referral_reward numeric := 5000;
begin
  new_username := public.generate_unique_username(new.raw_user_meta_data->>'username', new.email);
  new_code := public.generate_referral_code(new_username);
  ref := upper(nullif(trim(new.raw_user_meta_data->>'referred_by_code'),'') );

  insert into public.profiles(id,username,full_name,email,phone,referral_code,referred_by_code)
  values (
    new.id,
    new_username,
    coalesce(nullif(new.raw_user_meta_data->>'full_name',''),'Member'),
    new.email,
    new.raw_user_meta_data->>'phone',
    new_code,
    ref
  )
  on conflict (id) do update set
    email = excluded.email,
    updated_at = now();

  insert into public.wallets(user_id)
  values(new.id)
  on conflict(user_id) do nothing;

  if ref is not null then
    select id into referrer
    from public.profiles
    where upper(referral_code)=ref and id<>new.id
    limit 1;

    if referrer is not null then
      insert into public.referrals(referrer_id,referred_id,referral_code,status,reward)
      values(referrer,new.id,ref,'registered',referral_reward)
      on conflict(referred_id) do nothing;

      if found then
        update public.wallets
        set balance=balance+referral_reward,
            total_in=total_in+referral_reward,
            updated_at=now()
        where user_id=referrer;

        insert into public.transactions(user_id,type,amount,description)
        values(referrer,'referral_bonus',referral_reward,'Bonus referral member baru');
      end if;
    end if;
  end if;

  return new;
end;
$$;

-- Buat trigger hanya jika belum ada; tidak menghapus trigger yang sudah ada.
do $$
begin
  if not exists (
    select 1 from pg_trigger
    where tgname='on_auth_user_created'
      and tgrelid='auth.users'::regclass
  ) then
    create trigger on_auth_user_created
      after insert on auth.users
      for each row execute function public.handle_new_user();
  end if;
end
$$;

create or replace function public.get_login_email(p_username text)
returns text
language sql
security definer
set search_path=public
as $$
  select email from public.profiles
  where lower(username)=lower(trim(p_username))
  limit 1;
$$;

create or replace function public.claim_mission(p_mission_id bigint)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare
  uid uuid := auth.uid();
  m public.missions;
begin
  if uid is null then raise exception 'Belum login'; end if;

  select * into m
  from public.missions
  where id=p_mission_id and active=true;
  if not found then raise exception 'Misi tidak ditemukan'; end if;

  if exists (
    select 1 from public.user_missions
    where user_id=uid and mission_id=p_mission_id and status='completed'
  ) then
    raise exception 'Misi sudah diklaim';
  end if;

  insert into public.user_missions(user_id,mission_id,status,claimed_reward,completed_at)
  values(uid,p_mission_id,'completed',m.reward,now());

  update public.wallets
  set balance=balance+m.reward,
      total_in=total_in+m.reward,
      updated_at=now()
  where user_id=uid;

  insert into public.transactions(user_id,type,amount,reference_id,description)
  values(uid,'mission_reward',m.reward,p_mission_id,'Reward misi: '||m.title);

  update public.profiles
  set xp=xp+greatest(1,round(m.reward/1000)::int), updated_at=now()
  where id=uid;
end;
$$;

create or replace function public.request_withdrawal(
  p_amount numeric,
  p_method text,
  p_account_number text,
  p_account_name text
)
returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare
  uid uuid := auth.uid();
  wid bigint;
begin
  if uid is null then raise exception 'Belum login'; end if;
  if p_amount < 10000 then raise exception 'Minimum withdrawal Rp10.000'; end if;
  if coalesce(trim(p_method),'')='' or coalesce(trim(p_account_number),'')='' or coalesce(trim(p_account_name),'')='' then
    raise exception 'Data withdrawal belum lengkap';
  end if;

  update public.wallets
  set balance=balance-p_amount,
      total_out=total_out+p_amount,
      updated_at=now()
  where user_id=uid and balance>=p_amount;

  if not found then raise exception 'Saldo tidak mencukupi'; end if;

  insert into public.withdrawals(user_id,amount,method,account_number,account_name,status)
  values(uid,p_amount,p_method,p_account_number,p_account_name,'pending')
  returning id into wid;

  insert into public.transactions(user_id,type,amount,reference_id,description)
  values(uid,'withdrawal',p_amount,wid,'Pengajuan withdrawal');

  return wid;
end;
$$;

create or replace function public.admin_set_withdrawal_status(
  p_id bigint,
  p_status text,
  p_note text default null
)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare
  w public.withdrawals;
begin
  if not public.is_admin() then raise exception 'Akses admin diperlukan'; end if;
  if p_status not in ('approved','rejected','pending') then raise exception 'Status tidak valid'; end if;

  select * into w from public.withdrawals where id=p_id for update;
  if not found then raise exception 'Withdrawal tidak ditemukan'; end if;

  if w.status='pending' and p_status='rejected' then
    update public.wallets
    set balance=balance+w.amount,
        total_out=greatest(0,total_out-w.amount),
        updated_at=now()
    where user_id=w.user_id;

    insert into public.transactions(user_id,type,amount,reference_id,description)
    values(w.user_id,'withdrawal_refund',w.amount,w.id,'Refund withdrawal yang ditolak');
  elsif w.status='pending' and p_status='approved' then
    null;
  elsif w.status=p_status then
    raise exception 'Status withdrawal sudah %', p_status;
  else
    raise exception 'Perubahan status withdrawal tidak diizinkan';
  end if;

  update public.withdrawals
  set status=p_status,
      admin_note=p_note,
      processed_at=case when p_status='pending' then null else now() end
  where id=p_id;
end;
$$;

create or replace function public.admin_set_deposit_status(
  p_id bigint,
  p_status text,
  p_note text default null
)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare
  d public.deposits;
begin
  if not public.is_admin() then raise exception 'Akses admin diperlukan'; end if;
  if p_status not in ('approved','rejected','pending') then raise exception 'Status tidak valid'; end if;

  select * into d from public.deposits where id=p_id for update;
  if not found then raise exception 'Deposit tidak ditemukan'; end if;

  if d.status='pending' and p_status='approved' then
    update public.wallets
    set balance=balance+d.amount,
        total_in=total_in+d.amount,
        updated_at=now()
    where user_id=d.user_id;

    insert into public.transactions(user_id,type,amount,reference_id,description)
    values(d.user_id,'deposit',d.amount,d.id,'Deposit disetujui admin');
  elsif d.status='pending' and p_status='rejected' then
    null;
  elsif d.status=p_status then
    raise exception 'Status deposit sudah %', p_status;
  else
    raise exception 'Perubahan status deposit tidak diizinkan';
  end if;

  update public.deposits
  set status=p_status,
      admin_note=p_note,
      processed_at=case when p_status='pending' then null else now() end
  where id=p_id;
end;
$$;

-- Misi awal. Tidak ada misi referral yang bisa diklaim dua kali;
-- bonus referral berasal dari trigger pendaftaran.
insert into public.missions(title,description,reward) values
('Check-in Harian','Lakukan check-in dan selesaikan aktivitas hari ini.',1000),
('Lengkapi Profil','Lengkapi nama dan nomor HP pada profil.',3000),
('Aktivitas Harian','Selesaikan aktivitas harian yang tersedia.',2000),
('Bonus Konsisten','Pertahankan aktivitas akun secara rutin.',1500)
on conflict do nothing;

-- RLS
alter table public.profiles enable row level security;
alter table public.wallets enable row level security;
alter table public.missions enable row level security;
alter table public.user_missions enable row level security;
alter table public.referrals enable row level security;
alter table public.bank_accounts enable row level security;
alter table public.withdrawals enable row level security;
alter table public.deposits enable row level security;
alter table public.transactions enable row level security;

-- Membuat policy hanya jika belum ada. Tidak menghapus policy/data yang sudah ada.
do $$
begin
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='profiles' and policyname='profiles_select') then
    create policy profiles_select on public.profiles for select to authenticated using (id=auth.uid() or public.is_admin());
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='profiles' and policyname='profiles_update') then
    create policy profiles_update on public.profiles for update to authenticated using (id=auth.uid() or public.is_admin()) with check (id=auth.uid() or public.is_admin());
  end if;

  if not exists(select 1 from pg_policies where schemaname='public' and tablename='wallets' and policyname='wallets_select') then
    create policy wallets_select on public.wallets for select to authenticated using (user_id=auth.uid() or public.is_admin());
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='wallets' and policyname='admin_wallet_update') then
    create policy admin_wallet_update on public.wallets for update to authenticated using (public.is_admin()) with check (public.is_admin());
  end if;

  if not exists(select 1 from pg_policies where schemaname='public' and tablename='missions' and policyname='missions_select') then
    create policy missions_select on public.missions for select to authenticated using (active=true or public.is_admin());
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='missions' and policyname='admin_mission_all') then
    create policy admin_mission_all on public.missions for all to authenticated using (public.is_admin()) with check (public.is_admin());
  end if;

  if not exists(select 1 from pg_policies where schemaname='public' and tablename='user_missions' and policyname='user_missions_select') then
    create policy user_missions_select on public.user_missions for select to authenticated using (user_id=auth.uid() or public.is_admin());
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='user_missions' and policyname='admin_user_mission_all') then
    create policy admin_user_mission_all on public.user_missions for all to authenticated using (public.is_admin()) with check (public.is_admin());
  end if;

  if not exists(select 1 from pg_policies where schemaname='public' and tablename='referrals' and policyname='referrals_select') then
    create policy referrals_select on public.referrals for select to authenticated using (referrer_id=auth.uid() or referred_id=auth.uid() or public.is_admin());
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='referrals' and policyname='admin_referral_all') then
    create policy admin_referral_all on public.referrals for all to authenticated using (public.is_admin()) with check (public.is_admin());
  end if;

  if not exists(select 1 from pg_policies where schemaname='public' and tablename='bank_accounts' and policyname='bank_select') then
    create policy bank_select on public.bank_accounts for select to authenticated using (user_id=auth.uid() or public.is_admin());
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='bank_accounts' and policyname='bank_insert') then
    create policy bank_insert on public.bank_accounts for insert to authenticated with check (user_id=auth.uid());
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='bank_accounts' and policyname='bank_update') then
    create policy bank_update on public.bank_accounts for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='bank_accounts' and policyname='bank_delete') then
    create policy bank_delete on public.bank_accounts for delete to authenticated using (user_id=auth.uid());
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='bank_accounts' and policyname='admin_bank_all') then
    create policy admin_bank_all on public.bank_accounts for all to authenticated using (public.is_admin()) with check (public.is_admin());
  end if;

  if not exists(select 1 from pg_policies where schemaname='public' and tablename='withdrawals' and policyname='withdrawal_select') then
    create policy withdrawal_select on public.withdrawals for select to authenticated using (user_id=auth.uid() or public.is_admin());
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='withdrawals' and policyname='admin_withdrawal_all') then
    create policy admin_withdrawal_all on public.withdrawals for all to authenticated using (public.is_admin()) with check (public.is_admin());
  end if;

  if not exists(select 1 from pg_policies where schemaname='public' and tablename='deposits' and policyname='deposit_select') then
    create policy deposit_select on public.deposits for select to authenticated using (user_id=auth.uid() or public.is_admin());
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='deposits' and policyname='deposit_insert') then
    create policy deposit_insert on public.deposits for insert to authenticated with check (user_id=auth.uid());
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='deposits' and policyname='admin_deposit_all') then
    create policy admin_deposit_all on public.deposits for all to authenticated using (public.is_admin()) with check (public.is_admin());
  end if;

  if not exists(select 1 from pg_policies where schemaname='public' and tablename='transactions' and policyname='transaction_select') then
    create policy transaction_select on public.transactions for select to authenticated using (user_id=auth.uid() or public.is_admin());
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='transactions' and policyname='admin_transaction_all') then
    create policy admin_transaction_all on public.transactions for all to authenticated using (public.is_admin()) with check (public.is_admin());
  end if;
end
$$;

-- Hak eksekusi fungsi. Perubahan saldo hanya dilakukan melalui RPC yang aman.
revoke all on function public.claim_mission(bigint) from public;
grant execute on function public.claim_mission(bigint) to authenticated;
revoke all on function public.request_withdrawal(numeric,text,text,text) from public;
grant execute on function public.request_withdrawal(numeric,text,text,text) to authenticated;
revoke all on function public.admin_set_withdrawal_status(bigint,text,text) from public;
grant execute on function public.admin_set_withdrawal_status(bigint,text,text) to authenticated;
revoke all on function public.admin_set_deposit_status(bigint,text,text) from public;
grant execute on function public.admin_set_deposit_status(bigint,text,text) to authenticated;
revoke all on function public.get_login_email(text) from public;
grant execute on function public.get_login_email(text) to anon,authenticated;

-- SELECT yang dibutuhkan frontend.
grant select on public.missions to authenticated;
grant select on public.profiles,public.wallets,public.user_missions,public.referrals,
  public.bank_accounts,public.withdrawals,public.deposits,public.transactions to authenticated;
grant update on public.profiles to authenticated;
grant insert,update,delete on public.bank_accounts to authenticated;
grant insert on public.deposits to authenticated;

-- Setelah akun admin pertama dibuat:
-- update public.profiles set role='admin' where email='EMAIL_ADMIN_ANDA';
