-- SHORTPRO / MYSHORT - SUPABASE DATABASE
-- Jalankan seluruh file ini di Supabase SQL Editor.
-- Setelah itu masukkan URL + Publishable Key ke supabase-config.js.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  uid text unique not null default ('SP' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,10))),
  username text unique not null,
  full_name text not null default 'Member',
  email text not null,
  phone text,
  referral_code text unique not null,
  referred_by_code text,
  status text not null default 'Aktif',
  level text not null default 'LV 1',
  xp integer not null default 0,
  role text not null default 'member',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wallets (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  balance numeric(18,2) not null default 0,
  total_in numeric(18,2) not null default 0,
  total_out numeric(18,2) not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.missions (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  reward numeric(18,2) not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.user_missions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  mission_id bigint not null references public.missions(id) on delete cascade,
  status text not null default 'available',
  claimed_reward numeric(18,2) not null default 0,
  completed_at timestamptz,
  unique(user_id, mission_id)
);

create table if not exists public.referrals (
  id bigint generated by default as identity primary key,
  referrer_id uuid not null references public.profiles(id) on delete cascade,
  referred_id uuid not null unique references public.profiles(id) on delete cascade,
  referral_code text not null,
  status text not null default 'registered',
  reward numeric(18,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.bank_accounts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  method text not null,
  account_number text not null,
  account_name text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.withdrawals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  amount numeric(18,2) not null check(amount > 0),
  method text not null,
  account_number text not null,
  account_name text not null,
  status text not null default 'pending',
  admin_note text,
  created_at timestamptz not null default now(),
  processed_at timestamptz
);

create table if not exists public.deposits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  amount numeric(18,2) not null check(amount > 0),
  method text not null default 'DANA',
  status text not null default 'pending',
  proof_url text,
  admin_note text,
  created_at timestamptz not null default now(),
  processed_at timestamptz
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null,
  amount numeric(18,2) not null,
  reference_id bigint,
  description text,
  created_at timestamptz not null default now()
);

create or replace function public.generate_referral_code(p_username text)
returns text language plpgsql as $$
declare base text; code text;
begin
 base := upper(regexp_replace(coalesce(p_username,'USER'),'[^A-Za-z0-9]','','g'));
 base := left(base,4); if length(base)<3 then base := 'USER'; end if;
 loop
  code := base || floor(random()*900000+100000)::text;
  exit when not exists(select 1 from public.profiles where referral_code=code);
 end loop;
 return code;
end; $$;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
declare p_ref text; referrer uuid; new_code text;
begin
 new_code := public.generate_referral_code(coalesce(new.raw_user_meta_data->>'username',split_part(new.email,'@',1)));
 insert into public.profiles(id,username,full_name,email,phone,referral_code,referred_by_code)
 values(new.id,coalesce(new.raw_user_meta_data->>'username',split_part(new.email,'@',1)),coalesce(new.raw_user_meta_data->>'full_name','Member'),new.email,new.raw_user_meta_data->>'phone',new_code,new.raw_user_meta_data->>'referred_by_code');
 insert into public.wallets(user_id) values(new.id);
 p_ref := upper(nullif(new.raw_user_meta_data->>'referred_by_code',''));
 if p_ref is not null then
  select id into referrer from public.profiles where upper(referral_code)=p_ref limit 1;
  if referrer is not null and referrer <> new.id then
   insert into public.referrals(referrer_id,referred_id,referral_code) values(referrer,new.id,p_ref) on conflict(referred_id) do nothing;
  end if;
 end if;
 return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.get_login_email(p_username text)
returns text language sql security definer set search_path=public as $$
 select email from public.profiles where lower(username)=lower(p_username) limit 1;
$$;

create or replace function public.claim_mission(p_mission_id bigint)
returns void language plpgsql security definer set search_path=public as $$
declare uid uuid := auth.uid(); m public.missions; already boolean;
begin
 if uid is null then raise exception 'Belum login'; end if;
 select * into m from public.missions where id=p_mission_id and active=true;
 if not found then raise exception 'Misi tidak ditemukan'; end if;
 select exists(select 1 from public.user_missions where user_id=uid and mission_id=p_mission_id and status='completed') into already;
 if already then raise exception 'Misi sudah diklaim'; end if;
 insert into public.user_missions(user_id,mission_id,status,claimed_reward,completed_at) values(uid,p_mission_id,'completed',m.reward,now()) on conflict(user_id,mission_id) do update set status='completed',claimed_reward=excluded.claimed_reward,completed_at=excluded.completed_at;
 update public.wallets set balance=balance+m.reward,total_in=total_in+m.reward,updated_at=now() where user_id=uid;
 insert into public.transactions(user_id,type,amount,description) values(uid,'mission_reward',m.reward,'Reward: '||m.title);
end; $$;

create or replace function public.request_withdrawal(p_amount numeric,p_method text,p_account_number text,p_account_name text)
returns bigint language plpgsql security definer set search_path=public as $$
declare uid uuid := auth.uid(); wid bigint;
begin
 if uid is null then raise exception 'Belum login'; end if;
 if p_amount <= 0 then raise exception 'Jumlah tidak valid'; end if;
 update public.wallets set balance=balance-p_amount,total_out=total_out+p_amount,updated_at=now() where user_id=uid and balance>=p_amount;
 if not found then raise exception 'Saldo tidak mencukupi'; end if;
 insert into public.withdrawals(user_id,amount,method,account_number,account_name,status) values(uid,p_amount,p_method,p_account_number,p_account_name,'pending') returning id into wid;
 insert into public.transactions(user_id,type,amount,reference_id,description) values(uid,'withdrawal',p_amount,wid,'Pengajuan withdrawal');
 return wid;
end; $$;


create or replace function public.admin_set_withdrawal_status(p_id bigint,p_status text,p_note text default null)
returns void language plpgsql security definer set search_path=public as $$
declare w public.withdrawals;
begin
 if not public.is_admin() then raise exception 'Akses admin diperlukan'; end if;
 if p_status not in ('approved','rejected','pending') then raise exception 'Status tidak valid'; end if;
 select * into w from public.withdrawals where id=p_id for update;
 if not found then raise exception 'Withdrawal tidak ditemukan'; end if;
 if w.status='rejected' and p_status='rejected' then raise exception 'Sudah ditolak'; end if;
 if w.status='approved' and p_status='rejected' then raise exception 'Withdrawal sudah disetujui'; end if;
 if w.status='pending' and p_status='rejected' then
   update public.wallets set balance=balance+w.amount,total_out=greatest(0,total_out-w.amount),updated_at=now() where user_id=w.user_id;
   insert into public.transactions(user_id,type,amount,reference_id,description) values(w.user_id,'withdrawal_refund',w.amount,w.id,'Refund withdrawal yang ditolak');
 end if;
 update public.withdrawals set status=p_status,admin_note=p_note,processed_at=case when p_status='pending' then null else now() end where id=p_id;
end; $$;

insert into public.missions(title,description,reward) values
('Check-in Harian','Lakukan check-in hari ini.',1000),
('Lengkapi Profil','Lengkapi data profil member.',3000),
('Ajak Teman','Ajak member baru melalui referral.',5000),
('Selesaikan Misi','Selesaikan aktivitas misi yang tersedia.',2000)
on conflict do nothing;

-- RLS
alter table public.profiles enable row level security;
alter table public.wallets enable row level security;
alter table public.missions enable row level security;
alter table public.user_missions enable row level security;
alter table public.referrals enable row level security;
alter table public.bank_accounts enable row level security;
alter table public.withdrawals enable row level security;
alter table public.deposits enable row level security;
alter table public.transactions enable row level security;

create or replace function public.is_admin()
returns boolean language sql security definer set search_path=public as $$
 select exists(select 1 from public.profiles where id=auth.uid() and role='admin');
$$;

-- Drop/recreate policies to make this script repeatable
DO $$ declare r record; begin for r in select schemaname,tablename,policyname from pg_policies where schemaname='public' and tablename in ('profiles','wallets','missions','user_missions','referrals','bank_accounts','withdrawals','deposits','transactions') loop execute format('drop policy if exists %I on %I.%I',r.policyname,r.schemaname,r.tablename); end loop; end $$;

create policy profiles_select on public.profiles for select to authenticated using (id=auth.uid() or public.is_admin());
create policy profiles_update on public.profiles for update to authenticated using (id=auth.uid() or public.is_admin()) with check (id=auth.uid() or public.is_admin());

create policy wallets_select on public.wallets for select to authenticated using (user_id=auth.uid() or public.is_admin());
create policy missions_select on public.missions for select to authenticated using (active=true or public.is_admin());
create policy user_missions_select on public.user_missions for select to authenticated using (user_id=auth.uid() or public.is_admin());
create policy referrals_select on public.referrals for select to authenticated using (referrer_id=auth.uid() or referred_id=auth.uid() or public.is_admin());
create policy bank_select on public.bank_accounts for select to authenticated using (user_id=auth.uid() or public.is_admin());
create policy bank_insert on public.bank_accounts for insert to authenticated with check (user_id=auth.uid());
create policy bank_update on public.bank_accounts for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy withdrawal_select on public.withdrawals for select to authenticated using (user_id=auth.uid() or public.is_admin());
create policy deposit_select on public.deposits for select to authenticated using (user_id=auth.uid() or public.is_admin());
create policy transaction_select on public.transactions for select to authenticated using (user_id=auth.uid() or public.is_admin());

-- Admin can manage operational tables
create policy admin_wallet_update on public.wallets for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy admin_mission_all on public.missions for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy admin_user_mission_all on public.user_missions for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy admin_referral_all on public.referrals for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy admin_bank_all on public.bank_accounts for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy admin_withdrawal_all on public.withdrawals for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy admin_deposit_all on public.deposits for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy admin_transaction_all on public.transactions for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Function privileges
revoke all on function public.claim_mission(bigint) from public;
grant execute on function public.claim_mission(bigint) to authenticated;
revoke all on function public.request_withdrawal(numeric,text,text,text) from public;
grant execute on function public.request_withdrawal(numeric,text,text,text) to authenticated;
revoke all on function public.admin_set_withdrawal_status(bigint,text,text) from public;
grant execute on function public.admin_set_withdrawal_status(bigint,text,text) to authenticated;
revoke all on function public.get_login_email(text) from public;
grant execute on function public.get_login_email(text) to anon,authenticated;

-- Data API table privileges (RLS still applies)
grant select on public.missions to authenticated;
grant select on public.profiles,public.wallets,public.user_missions,public.referrals,public.bank_accounts,public.withdrawals,public.deposits,public.transactions to authenticated;
grant update on public.profiles to authenticated;
grant insert,update on public.bank_accounts to authenticated;

-- After your first account is registered, make it admin from SQL Editor:
-- update public.profiles set role='admin' where email='YOUR_ADMIN_EMAIL';
